// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Alarm Clock

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_btnTimerHrs;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_btnTimerMin;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_btnTimerSec;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_btnTimerReset;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_btnTimerStartStop;
extern lv_obj_t *ui_Label17;
extern void ui_event_Button12( lv_event_t * e);
extern lv_obj_t *ui_Button12;
extern lv_obj_t *ui_Label18;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

