// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Alarm Clock

#include "ui.h"

lv_obj_t *uic_chkAlarm;
lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_lblCurrentTime = NULL;lv_obj_t *ui_chkAlarm = NULL;lv_obj_t *ui_Button5 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label8 = NULL;
// event funtions
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen4_screen_init);
}
}

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblCurrentTime = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_lblCurrentTime, LV_SIZE_CONTENT);  /// 11
lv_obj_set_height( ui_lblCurrentTime, LV_SIZE_CONTENT);   /// 11
lv_obj_set_x( ui_lblCurrentTime, 4 );
lv_obj_set_y( ui_lblCurrentTime, -32 );
lv_obj_set_align( ui_lblCurrentTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblCurrentTime,"12:34 AM");
lv_obj_set_style_text_font(ui_lblCurrentTime, &ui_font_Digital3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_chkAlarm = lv_checkbox_create(ui_Screen3);
lv_checkbox_set_text(ui_chkAlarm,"Alarm ON");
lv_obj_set_width( ui_chkAlarm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_chkAlarm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_chkAlarm, -46 );
lv_obj_set_y( ui_chkAlarm, 9 );
lv_obj_set_align( ui_chkAlarm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_chkAlarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Button5 = lv_button_create(ui_Screen3);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 50);
lv_obj_set_x( ui_Button5, -3 );
lv_obj_set_y( ui_Button5, 86 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Button5);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Next");

ui_Label8 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -104 );
lv_obj_set_y( ui_Label8, -103 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Current Time:");

lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
uic_chkAlarm = ui_chkAlarm;

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_lblCurrentTime= NULL;
uic_chkAlarm= NULL;
ui_chkAlarm= NULL;
ui_Button5= NULL;
ui_Label7= NULL;
ui_Label8= NULL;

}
