// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Alarm Clock

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_lblAlarmTime;
extern lv_obj_t *ui_btnAlarmHrs;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_btnAlarmMin;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_btnAlarmAmPm;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label11;
extern void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

