// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Alarm Clock

#include "ui.h"
#include "button_handler.h"

lv_obj_t *ui_Screen5 = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_Label14 = NULL;lv_obj_t *ui_btnTimerHrs = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_btnTimerMin = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_btnTimerSec = NULL;lv_obj_t *ui_Label15 = NULL;lv_obj_t *ui_btnTimerReset = NULL;lv_obj_t *ui_Label16 = NULL;lv_obj_t *ui_btnTimerStartStop = NULL;lv_obj_t *ui_Label17 = NULL;lv_obj_t *ui_Button12 = NULL;lv_obj_t *ui_Label18 = NULL;
// event funtions
void ui_event_Button12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen3_screen_init);
}
}

// build funtions

void ui_Screen5_screen_init(void)
{
ui_Screen5 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -115 );
lv_obj_set_y( ui_Label13, -99 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Set Timer:");

ui_Label14 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, -1 );
lv_obj_set_y( ui_Label14, -64 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"00:00:00");
lv_obj_set_style_text_font(ui_Label14, &ui_font_Digital3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnTimerHrs = lv_button_create(ui_Screen5);
lv_obj_set_width( ui_btnTimerHrs, 64);
lv_obj_set_height( ui_btnTimerHrs, 42);
lv_obj_set_x( ui_btnTimerHrs, -94 );
lv_obj_set_y( ui_btnTimerHrs, -18 );
lv_obj_set_align( ui_btnTimerHrs, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTimerHrs, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnTimerHrs, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnTimerHrs, lv_color_hex(0x0CE27D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTimerHrs, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_btnTimerHrs);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Hr");

ui_btnTimerMin = lv_button_create(ui_Screen5);
lv_obj_set_width( ui_btnTimerMin, 60);
lv_obj_set_height( ui_btnTimerMin, 44);
lv_obj_set_x( ui_btnTimerMin, -3 );
lv_obj_set_y( ui_btnTimerMin, -18 );
lv_obj_set_align( ui_btnTimerMin, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTimerMin, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnTimerMin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnTimerMin, lv_color_hex(0x0E25DB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTimerMin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_btnTimerMin);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Min");

ui_btnTimerSec = lv_button_create(ui_Screen5);
lv_obj_set_width( ui_btnTimerSec, 74);
lv_obj_set_height( ui_btnTimerSec, 42);
lv_obj_set_x( ui_btnTimerSec, 96 );
lv_obj_set_y( ui_btnTimerSec, -17 );
lv_obj_set_align( ui_btnTimerSec, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTimerSec, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnTimerSec, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnTimerSec, lv_color_hex(0xDE1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTimerSec, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_btnTimerSec);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Sec");

ui_btnTimerReset = lv_button_create(ui_Screen5);
lv_obj_set_width( ui_btnTimerReset, 77);
lv_obj_set_height( ui_btnTimerReset, 31);
lv_obj_set_x( ui_btnTimerReset, -86 );
lv_obj_set_y( ui_btnTimerReset, 28 );
lv_obj_set_align( ui_btnTimerReset, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTimerReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnTimerReset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnTimerReset, lv_color_hex(0xDE1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTimerReset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_btnTimerReset);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Reset");

ui_btnTimerStartStop = lv_button_create(ui_Screen5);
lv_obj_set_width( ui_btnTimerStartStop, 114);
lv_obj_set_height( ui_btnTimerStartStop, 31);
lv_obj_set_x( ui_btnTimerStartStop, 66 );
lv_obj_set_y( ui_btnTimerStartStop, 27 );
lv_obj_set_align( ui_btnTimerStartStop, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTimerStartStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnTimerStartStop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnTimerStartStop, lv_color_hex(0x0CE27D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTimerStartStop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_btnTimerStartStop);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Start/Stop");

ui_Button12 = lv_button_create(ui_Screen5);
lv_obj_set_width( ui_Button12, 100);
lv_obj_set_height( ui_Button12, 50);
lv_obj_set_x( ui_Button12, -3 );
lv_obj_set_y( ui_Button12, 86 );
lv_obj_set_align( ui_Button12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label18 = lv_label_create(ui_Button12);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Next");

lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);

// add by LS
lv_obj_add_event_cb(ui_btnTimerHrs, ui_event_global_button_handler, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnTimerMin, ui_event_global_button_handler, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnTimerSec, ui_event_global_button_handler, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnTimerReset, ui_event_global_button_handler, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnTimerStartStop, ui_event_global_button_handler, LV_EVENT_ALL, NULL);


}

void ui_Screen5_screen_destroy(void)
{
   if (ui_Screen5) lv_obj_del(ui_Screen5);

// NULL screen variables
ui_Screen5= NULL;
ui_Label13= NULL;
ui_Label14= NULL;
ui_btnTimerHrs= NULL;
ui_Label4= NULL;
ui_btnTimerMin= NULL;
ui_Label5= NULL;
ui_btnTimerSec= NULL;
ui_Label15= NULL;
ui_btnTimerReset= NULL;
ui_Label16= NULL;
ui_btnTimerStartStop= NULL;
ui_Label17= NULL;
ui_Button12= NULL;
ui_Label18= NULL;

}
