// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Alarm Clock

#include "ui.h"
#include "button_handler.h"

lv_obj_t *ui_Screen4 = NULL;lv_obj_t *ui_lblAlarmTime = NULL;lv_obj_t *ui_btnAlarmHrs = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_btnAlarmMin = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_btnAlarmAmPm = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_Button7 = NULL;lv_obj_t *ui_Label12 = NULL;
// event funtions
void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
}
}

// build funtions

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_lblAlarmTime = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_lblAlarmTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblAlarmTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblAlarmTime, -13 );
lv_obj_set_y( ui_lblAlarmTime, -39 );
lv_obj_set_align( ui_lblAlarmTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblAlarmTime,"12:00 PM");
lv_obj_set_style_text_font(ui_lblAlarmTime, &ui_font_Digital3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnAlarmHrs = lv_button_create(ui_Screen4);
lv_obj_set_width( ui_btnAlarmHrs, 51);
lv_obj_set_height( ui_btnAlarmHrs, 29);
lv_obj_set_x( ui_btnAlarmHrs, -99 );
lv_obj_set_y( ui_btnAlarmHrs, 16 );
lv_obj_set_align( ui_btnAlarmHrs, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnAlarmHrs, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnAlarmHrs, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnAlarmHrs, lv_color_hex(0x0CE27D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnAlarmHrs, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_btnAlarmHrs);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Hrs");

ui_btnAlarmMin = lv_button_create(ui_Screen4);
lv_obj_set_width( ui_btnAlarmMin, 51);
lv_obj_set_height( ui_btnAlarmMin, 36);
lv_obj_set_x( ui_btnAlarmMin, -24 );
lv_obj_set_y( ui_btnAlarmMin, 15 );
lv_obj_set_align( ui_btnAlarmMin, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnAlarmMin, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnAlarmMin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnAlarmMin, lv_color_hex(0x0E25DB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnAlarmMin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_btnAlarmMin);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Min");

ui_btnAlarmAmPm = lv_button_create(ui_Screen4);
lv_obj_set_width( ui_btnAlarmAmPm, 70);
lv_obj_set_height( ui_btnAlarmAmPm, 36);
lv_obj_set_x( ui_btnAlarmAmPm, 59 );
lv_obj_set_y( ui_btnAlarmAmPm, 16 );
lv_obj_set_align( ui_btnAlarmAmPm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnAlarmAmPm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnAlarmAmPm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnAlarmAmPm, lv_color_hex(0xDE1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnAlarmAmPm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_btnAlarmAmPm);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"AM/PM");

ui_Label11 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -115 );
lv_obj_set_y( ui_Label11, -100 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Set Alarm:");

ui_Button7 = lv_button_create(ui_Screen4);
lv_obj_set_width( ui_Button7, 100);
lv_obj_set_height( ui_Button7, 50);
lv_obj_set_x( ui_Button7, -22 );
lv_obj_set_y( ui_Button7, 83 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_Button7);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Next");

lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);

// add by LS
lv_obj_add_event_cb(ui_btnAlarmHrs, ui_event_global_button_handler, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnAlarmMin, ui_event_global_button_handler, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnAlarmAmPm, ui_event_global_button_handler, LV_EVENT_ALL, NULL);


uic_chkAlarm = ui_chkAlarm;

}

void ui_Screen4_screen_destroy(void)
{
   if (ui_Screen4) lv_obj_del(ui_Screen4);

// NULL screen variables
ui_Screen4= NULL;
ui_lblAlarmTime= NULL;
ui_btnAlarmHrs= NULL;
ui_Label10= NULL;
ui_btnAlarmMin= NULL;
ui_Label1= NULL;
ui_btnAlarmAmPm= NULL;
ui_Label2= NULL;
ui_Label11= NULL;
ui_Button7= NULL;
ui_Label12= NULL;

}
